service: ImageUploader

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
package:
    patterns:
        - '!node_modules/**'

provider:
    name: aws
    runtime: nodejs14.x
    iamRoleStatements:
        - Effect: Allow
          Action:
              - s3:PutObject
              - s3:GetObject
          Resource: 'arn:aws:s3:::${self:custom.bucketName}/*'

custom:
    bucketName: ${env:S3_BUCKET_NAME}
    serverless-offline:
        port: 9229

functions:
    imUpload:
        handler: src/upload.handler
        events:
            - http:
                  path: /
                  method: post
    extractData:
        handler: src/extractor.handler
        events:
            - s3:
                  bucket: ${self:custom.bucketName}
                  event: s3:ObjectCreated:*
